language: python

# for container-y goodness:
sudo: false

python:
  - "2.7"

# command to install dependencies
install: 
- "pip install --upgrade pip setuptools"
- "pip install -Ue .[test]"

# command to run tests, e.g. python setup.py test
script: coverage run --source mailinglogger -m pytest

after_success:
  - coveralls

jobs:
  include:

    - stage: coverage
      if: type != cron
      python: 2.7
      after_success: skip

      install: "pip install -U coveralls-check"
      script: "coveralls-check $TRAVIS_COMMIT"

